Update to ubuntu 26.04-lts (except for qgis 3 non-ltr), add qgis-4-release-nightly and dev (master) builds

diff --git a/.github/workflows/qgis-server.yml b/.github/workflows/qgis-server.yml
--- a/.github/workflows/qgis-server.yml
+++ b/.github/workflows/qgis-server.yml
@@ -1,10 +1,12 @@
 name: Publish qwc-qgis-server docker images
 
 env:
-  UBUNTU_RELEASE: noble
+  UBUNTU_RELEASE: resolute
 
 on:
   push:
+    branches:
+      - main
   workflow_dispatch:
   schedule:
     - cron: "0 6 * * TUE" # every Tuesday on 6:00 UTC
@@ -15,14 +17,19 @@ jobs:
     steps:
       - uses: actions/checkout@master
 
+      # Latest 3.x LTR release, also built as an image with ODBC driver
       - name: Get version tag QGIS LTR
         id: get_tag_qgis_ltr
         run: |
-          VERSION_TRIPLE=$(curl -Ls https://ubuntu.qgis.org/ubuntu-ltr/dists/${{env.UBUNTU_RELEASE}}/main/binary-amd64/Packages | grep -A 2 "Package: qgis-server$" | grep Version | head -1 | sed -n 's/.*:\([0-9]\+\.[0-9]\+\.[0-9]\+\).*/\1/p')
+          VERSION_TRIPLE=$(curl -Ls https://ubuntu.qgis.org/ubuntu-ltr/dists/${{env.UBUNTU_RELEASE}}/main/binary-amd64/Packages | grep -A 2 "Package: qgis-server$" | grep -E "^Version: [0-9]+:3" | head -1 | sed -n 's/.*:\([0-9]\+\.[0-9]\+\.[0-9]\+\).*/\1/p')
           VERSION_MINOR=$(echo ${VERSION_TRIPLE} | sed -E 's/^([0-9]+\.[0-9]+).*/\1/')
-          echo "version=$VERSION_TRIPLE" >> $GITHUB_OUTPUT
-          echo "minor=$VERSION_MINOR" >> $GITHUB_OUTPUT
+          if [[ -z "$VERSION_TRIPLE" ]]; then
+            echo "Failed to determine version"
+            exit 1
+          fi
           echo "tags=$VERSION_TRIPLE,$VERSION_MINOR,latest-ltr" >> $GITHUB_OUTPUT
+          echo "tags_odbc=$VERSION_TRIPLE-odbc,$VERSION_MINOR-odbc" >> $GITHUB_OUTPUT
+          echo "QGIS 3 latest LTR release: $VERSION_TRIPLE"
 
       - name: Build and publish docker image for QGIS Server LTR
         uses: elgohr/Publish-Docker-Github-Action@v5
@@ -44,20 +51,79 @@ jobs:
           name: sourcepole/qwc-qgis-server
           username: ${{ secrets.DOCKER_HUB_USER }}
           password: ${{ secrets.DOCKER_HUB_PASSWORD }}
-          tags: "${{ steps.get_tag_qgis_ltr.outputs.version }}-odbc,${{ steps.get_tag_qgis_ltr.outputs.minor }}-odbc"
+          tags: "${{ steps.get_tag_qgis_3_ltr.outputs.tags_odbc }}"
           workdir: .
           dockerfile: Dockerfile-odbc
           buildargs: UBUNTU_RELEASE,QGIS_REPO
 
-
-      - name: Get version tag QGIS
-        id: get_tag_qgis
+      # Latest 3.x release
+      # NOTE: the qgis ubuntu repo ships qgis 4.x for ubuntu LTS versions newer than noble
+      - name: Get version tag QGIS 3
+        id: get_tag_qgis_3
         run: |
-          VERSION_TRIPLE=$(curl -Ls https://ubuntu.qgis.org/ubuntu/dists/${{env.UBUNTU_RELEASE}}/main/binary-amd64/Packages | grep -A 2 "Package: qgis-server$" | grep Version | head -1 | sed -n 's/.*:\([0-9]\+\.[0-9]\+\.[0-9]\+\).*/\1/p')
+          VERSION_TRIPLE=$(curl -Ls https://ubuntu.qgis.org/ubuntu/dists/noble/main/binary-amd64/Packages | grep -A 2 "Package: qgis-server$" | grep -E "^Version: [0-9]+:3" | head -1 | sed -n 's/.*:\([0-9]\+\.[0-9]\+\.[0-9]\+\).*/\1/p')
           VERSION_MINOR=$(echo ${VERSION_TRIPLE} | sed -E 's/^([0-9]+\.[0-9]+).*/\1/')
-          echo "tags=$VERSION_TRIPLE,$VERSION_MINOR,latest" >> $GITHUB_OUTPUT
+          if [[ -z "$VERSION_TRIPLE" ]]; then
+            echo "Failed to determine version"
+            exit 1
+          fi
+          echo "tags=$VERSION_TRIPLE,$VERSION_MINOR,latest-3" >> $GITHUB_OUTPUT
+          echo "QGIS 3 latest release: $VERSION_TRIPLE"
 
-      - name: Build and publish docker image for QGIS Server
+      - name: Build and publish docker image for QGIS Server 3
+        uses: elgohr/Publish-Docker-Github-Action@v5
+        env:
+          QGIS_REPO: ubuntu
+          UBUNTU_RELEASE: noble
+        with:
+          name: sourcepole/qwc-qgis-server
+          username: ${{ secrets.DOCKER_HUB_USER }}
+          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
+          tags: "${{ steps.get_tag_qgis_3.outputs.tags }}"
+          workdir: .
+          buildargs: UBUNTU_RELEASE,QGIS_REPO
+
+      # Release nightlies of release latest 3.x release branch
+      # NOTE: the qgis ubuntu repo ships qgis 4.x for ubuntu LTS versions newer than noble
+      - name: Get version tag QGIS 3 release nightly
+        id: get_tag_qgis_3_release_nightly
+        run: |
+          VERSION_TRIPLE=$(curl -Ls https://ubuntu.qgis.org/ubuntu-nightly-release/dists/noble/main/binary-amd64/Packages | grep -A 2 "Package: qgis-server$" | grep -E "^Version: [0-9]+:3" | head -1 | sed -n 's/.*:\([0-9]\+\.[0-9]\+\.[0-9]\+\).*/\1/p')
+          VERSION_MINOR=$(echo ${VERSION_TRIPLE} | sed -E 's/^([0-9]+\.[0-9]+).*/\1/')
+          if [[ -z "$VERSION_TRIPLE" ]]; then
+            echo "Failed to determine version"
+            exit 1
+          fi
+          echo "tags=${VERSION_TRIPLE}-nightly,${VERSION_MINOR}-nightly,latest-3-nightly" >> $GITHUB_OUTPUT
+          echo "QGIS 3 latest nightly release: $VERSION_TRIPLE"
+
+      - name: Build and publish docker image for QGIS Server 3 release nightly
+        uses: elgohr/Publish-Docker-Github-Action@v5
+        env:
+          QGIS_REPO: ubuntu-nightly-release
+          UBUNTU_RELEASE: noble
+        with:
+          name: sourcepole/qwc-qgis-server
+          username: ${{ secrets.DOCKER_HUB_USER }}
+          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
+          tags: "${{ steps.get_tag_qgis_3_release_nightly.outputs.tags }}"
+          workdir: .
+          buildargs: UBUNTU_RELEASE,QGIS_REPO
+
+      # Latest 4.x release
+      - name: Get version tag QGIS 4
+        id: get_tag_qgis_4
+        run: |
+          VERSION_TRIPLE=$(curl -Ls https://ubuntu.qgis.org/ubuntu/dists/${{env.UBUNTU_RELEASE}}/main/binary-amd64/Packages | grep -A 2 "Package: qgis-server$" | grep -E "^Version: [0-9]+:4" | head -1 | sed -n 's/.*:\([0-9]\+\.[0-9]\+\.[0-9]\+\).*/\1/p')
+          VERSION_MINOR=$(echo ${VERSION_TRIPLE} | sed -E 's/^([0-9]+\.[0-9]+).*/\1/')
+          if [[ -z "$VERSION_TRIPLE" ]]; then
+            echo "Failed to determine version"
+            exit 1
+          fi
+          echo "tags=$VERSION_TRIPLE,$VERSION_MINOR,latest-4" >> $GITHUB_OUTPUT
+          echo "QGIS 4 latest release: $VERSION_TRIPLE"
+
+      - name: Build and publish docker image for QGIS Server 4
         uses: elgohr/Publish-Docker-Github-Action@v5
         env:
           QGIS_REPO: ubuntu
@@ -65,19 +131,24 @@ jobs:
           name: sourcepole/qwc-qgis-server
           username: ${{ secrets.DOCKER_HUB_USER }}
           password: ${{ secrets.DOCKER_HUB_PASSWORD }}
-          tags: "${{ steps.get_tag_qgis.outputs.tags }}"
+          tags: "${{ steps.get_tag_qgis_4.outputs.tags }}"
           workdir: .
           buildargs: UBUNTU_RELEASE,QGIS_REPO
 
-
-      - name: Get version tag QGIS release nightly
-        id: get_tag_qgis_nightly
+      # Release nightlies of release latest 4.x release branch
+      - name: Get version tag QGIS 4 release nightly
+        id: get_tag_qgis_4_release_nightly
         run: |
-          VERSION_TRIPLE=$(curl -Ls https://ubuntu.qgis.org/ubuntu-nightly-release/dists/${{env.UBUNTU_RELEASE}}/main/binary-amd64/Packages | grep -A 2 "Package: qgis-server$" | grep Version | head -1 | sed -n 's/.*:\([0-9]\+\.[0-9]\+\.[0-9]\+\).*/\1/p')
+          VERSION_TRIPLE=$(curl -Ls https://ubuntu.qgis.org/ubuntu/dists/${{env.UBUNTU_RELEASE}}/main/binary-amd64/Packages | grep -A 2 "Package: qgis-server$" | grep -E "^Version: [0-9]+:4" | head -1 | sed -n 's/.*:\([0-9]\+\.[0-9]\+\.[0-9]\+\).*/\1/p')
           VERSION_MINOR=$(echo ${VERSION_TRIPLE} | sed -E 's/^([0-9]+\.[0-9]+).*/\1/')
-          echo "tags=${VERSION_TRIPLE}-nightly,${VERSION_MINOR}-nightly,latest-nightly" >> $GITHUB_OUTPUT
+          if [[ -z "$VERSION_TRIPLE" ]]; then
+            echo "Failed to determine version"
+            exit 1
+          fi
+          echo "tags=${VERSION_TRIPLE}-nightly,${VERSION_MINOR}-nightly,latest-4-nightly" >> $GITHUB_OUTPUT
+          echo "QGIS 4 latest nightly release: $VERSION_TRIPLE"
 
-      - name: Build and publish docker image for QGIS Server nightly
+      - name: Build and publish docker image for QGIS Server 4 release nightly
         uses: elgohr/Publish-Docker-Github-Action@v5
         env:
           QGIS_REPO: ubuntu-nightly-release
@@ -85,26 +156,31 @@ jobs:
           name: sourcepole/qwc-qgis-server
           username: ${{ secrets.DOCKER_HUB_USER }}
           password: ${{ secrets.DOCKER_HUB_PASSWORD }}
-          tags: "${{ steps.get_tag_qgis_nightly.outputs.tags }}"
+          tags: "${{ steps.get_tag_qgis_4_release_nightly.outputs.tags }}"
           workdir: .
           buildargs: UBUNTU_RELEASE,QGIS_REPO
 
-      - name: Get version tag QGIS 4
-        id: get_tag_qgis_4
+      # Development nightlies (latest master)
+      - name: Get version tag QGIS development nightly
+        id: get_tag_qgis_dev_nightly
         run: |
-          VERSION_TRIPLE=$(curl -Ls https://ubuntu.qgis.org/ubuntu/dists/plucky/main/binary-amd64/Packages | grep -A 2 "Package: qgis-server$" | grep Version | head -1 | sed -n 's/.*:\([0-9]\+\.[0-9]\+\.[0-9]\+\).*/\1/p')
+          VERSION_TRIPLE=$(curl -Ls https://qgis.org/downloads/debian-nightly/dists/${{env.UBUNTU_RELEASE}}/main/binary-amd64/Packages | grep -A 2 "Package: qgis-server$" | grep Version | head -1 | sed -n 's/.*:\([0-9]\+\.[0-9]\+\.[0-9]\+\).*/\1/p')
           VERSION_MINOR=$(echo ${VERSION_TRIPLE} | sed -E 's/^([0-9]+\.[0-9]+).*/\1/')
-          echo "tags=$VERSION_TRIPLE,$VERSION_MINOR,latest-4" >> $GITHUB_OUTPUT
+          if [[ -z "$VERSION_TRIPLE" ]]; then
+            echo "Failed to determine version"
+            exit 1
+          fi
+          echo "tags=${VERSION_TRIPLE}-dev,${VERSION_MINOR}-dev,dev" >> $GITHUB_OUTPUT
+          echo "QGIS latest development version: $VERSION_TRIPLE"
 
-      - name: Build and publish docker image for QGIS Server 4
+      - name: Build and publish docker image for QGIS Server development nightly
         uses: elgohr/Publish-Docker-Github-Action@v5
         env:
-          QGIS_REPO: ubuntu
-          UBUNTU_RELEASE: plucky
+          QGIS_REPO: ubuntu-nightly
         with:
           name: sourcepole/qwc-qgis-server
           username: ${{ secrets.DOCKER_HUB_USER }}
           password: ${{ secrets.DOCKER_HUB_PASSWORD }}
-          tags: "${{ steps.get_tag_qgis_4.outputs.tags }}"
+          tags: "${{ steps.get_tag_qgis_4_dev_nightly.outputs.tags }}"
           workdir: .
           buildargs: UBUNTU_RELEASE,QGIS_REPO
